/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package custom.collector;

import java.util.*;
import java.util.stream.*;

public class App {
    public static void main(String[] args) {
        Map<Boolean, List<Integer>> map = Stream.of(1, 2, 3, 1, 9, 2, 5, 3, 4, 8, 2)
                .collect(new PartitioningByUniquenessCollector<>());
        map.forEach((key, nums) -> {
            System.out.println();
            System.out.println(key.toString());
            nums.forEach(System.out::print);
        });
    }
}
